<?php

$CONTENT = array(
	'GRAB: U cant control what happens 2 u, but u can control ur attitude toward wat happens to u-thru this u master change dan allowing it to master u. - Brian T.',
	'GRAB: We judge success by the index of our salaries or d size of r automobiles, rather dan by d quality of r service relationship to humanity. - Martin L.K.',
	'GRAB: Let yourself fall in love. If you have not done so already, you are wasting your life.  - D. H. Lawrence',
	'GRAB: "Ang 2nay na kacyahan ay hnd mku2ha sa bulsa na puno ng pera.Ito ay mku2ha s puso n puno ng pgma2hal at sa icp n puno ng mli2gyang ala-ala." -Kayne Olto',
	'GRAB: "Be with people who knows your worth. You dont need too many people to be happy. Just a few real ones who appreciate you for who you are" -Zae Raullo',
	'GRAB: "Dont be reckless with other peoples hearts, and dont put up with people that are reckless with yours." -Kurt Vonnegut,  Jr. Novelist',
	'GRAB: "Dont count what you lost, cherish what you have & plan what to gain because past never returns but future may fulfill the loss." -Trixie Pinch',
	'GRAB: "Everyone will not get everything This is the RULE of LIFE, Dont try to get which is not yours. But dont dare to loose which is yours." -Ben Stein',
	'GRAB: "God didnt promise days w/o pain, laughter w/o sorrow, sun w/o rain, but He did promise strength 4 d day, comfort 4 d tears & light for d way." -David Cliff',
	'GRAB: "Hope 4 d best, prpare 4 d worst, fight 4 wat you bliv in, expect nothing, and u\'ll nver be disappointed in all that life throws at you." -Lea Madrid',
	'GRAB: "if  u dnt go after what u want, ull never get it, if u dnt ask , d answer is no,if  u dnt step forward,u r always in the same place" -Angelo Sting',
	'GRAB: "In lyf, God dsnt giv U d ppol U want. Instead, he gives U d pool u nid. To teach u, to hurt u, to love u & make u exactly d way U shud be." -Liza Gotale',
	'GRAB: "Makakabalik ka nga sa LUGAR, pero hindi sa PANAHON. Makikita mo ulit ang taong minahal mo, pero hindi na mauulit ang naramdaman ninyo noon." -Meld Amplyo',
	'GRAB: "Never search ur happiness in others which will make u feel alone, but search it in urself u will feel happy even if u are left alone." -Trixie Pinch',
	'GRAB: "NOT all fingers r of same LENGTH, but wen dey r BENT, all stand n EQUAL length. LIFE bcomes easy wen we BEND & ADJUST to certain situations." -Kevie Lim',
	'GRAB: "Only a few people can feel the rain, others just get wet. Only a few lovers can feel the pain of depart, others just find another." -Vhon Grane',
	'GRAB: "Prayer is the most powerful against trials, the most effective medicine against sickness and the most valuable gift to someone we care for" -Stidian',
	'GRAB: "Samtyms ul break down & samtyms ul cry but jst rmember that its not a sign of weakness, its a sign that uve bin strong for too long." -Miaka Suy',
	'GRAB: "Some mothers are kissing mothers and some are scolding mothers, but it is love just the same, and most mothers kiss and scold together." -Pearl S. Buck',
	'GRAB: "Sometimes we have to run away from the people we love, not because we want them to realize our worth. but for us to realize our own worth." -Merideth',
	'GRAB: "Surround urself w/ pipol who know ur worth. U dont need too many pipol 2b happy, jst a FEW REAL ones who appreciate u for who you are." -Joyce Nacede',
	'GRAB: "Things dnt always go how U want dem 2b. Most of d tym, they go how God plannd dem 2b & eventually you\'ll realize its a lot more better." -Donne Saint',
	'GRAB: "To accomplish our goal we need to stand strong to the ground even when the strongest storm challenges us to turn our back & walk away." -Sameer Dhingra',
	'GRAB: "To pray against temptations and yet to experiment with them, is like thrusting your fingers into the fire and praying they dont be burned." -Zafra Hould',
	'GRAB: "We hyd 2b found.We walk away 2see hu wil folow. We cry 2see hu wil wipe away our tears.We let our harts get broken 2see hu wil fix them." -Vic Fausto',
	'GRAB: "When we make decisions there are always 2 thoughts to consider. If youre half way sure, FORGET IT. If youre sure, THINK AGAIN." -Ian Cargo',
	'GRAB: "When youre tired of everything and almost wanna quit, always put this into your mind: A good fighter will never ever be a loser." -Mafie Caney',
	'GRAB: "You can close your eyes from the things you dont want to see but you can never close your heart from the things you dont want to feel." -Melissa Fray',
	'GRAB: “A mother is a person who seeing there are only four pieces of pie for five people, promptly announces she never did care for pie." -Tenneva Jordan',
	'GRAB: “d Real Art Of Conversation Is Not Only To Say d Right Thing At d Right Time, But Also To Leave Unsaid d Wrong Thing At d Tempting Moment." -Stid Worth',
	'GRAB: “Smtyms we think dat we waste our words. Nd we waste our mments. Nd we dnt tke d tym 2 say d things dat r in our harts wen we hav d chance." -Mice Rolf',
	'GRAB: “To love sam1 unconditionally means dat U love d person exactly as dey r, exactly as dey were before & exactly as dey will b in d future." -Cherie Carter',
	'GRAB: 85% of the population can curl their tongue into a tube.',
	'GRAB: A bird called the bee eater in areas of Africa thinks that riding around on the backs of other animals is fun!',
	'GRAB: A butterfly has its taste receptors in its feet!',
	'GRAB: A cockroach can live for up to 3 weeks without its head!',
	'GRAB: A female seahorse lets her husband store her babies inside his stomach!',
	'GRAB: A heart can be broken; but it keeps beating just the same. -----Fried Green Tomatoes',
	'GRAB: A human’s small intestine is 6 meters long.',
	'GRAB: A mosquito flaps its wings 500 times a second.',
	'GRAB: A slug has four noses.',
	'GRAB: A snail can sleep for 3 years straight!',
	'GRAB: A sneeze travels at over 100 miles per hour.',
	'GRAB: About 80 percent of the Earths animals are insects!',
	'GRAB: Action may not always bring happiness; but there is no happiness without action. -- Benjamin Disraeli',
	'GRAB: Adult male giraffes bang their long necks together in a form of ritual fighting, during which no harm is done to either giraffe.',
	'GRAB: An okapi’s tongue can grow to be 17 inches long.',
	'GRAB: An owl’s eyes are bigger than its brain.',
	'GRAB: Anybody can do anything with himself that he really wants to and makes up his mind to do. We r capable of greater things than we realize. --Norman P.',
	'GRAB: Baby robins eat 14 feet of earthworms every day!',
	'GRAB: Being deeply loved by someone gives you strength; loving someone deeply gives you courage. ---Lao Tzu',
	'GRAB: Birds save energy by flying in a “V” formation.',
	'GRAB: Blue jays often forget where they hide winter supplies of food.',
	'GRAB: By the time you are 70 you will have easily drunk over 12000 gallons of water.',
	'GRAB: Chimpanzees use tools more than any other animal except man.',
	'GRAB: Coughing can cause air to move through your windpipe faster than the speed of sound, over a thousand feet per second!',
	'GRAB: Cows have four-chambered stomachs.',
	'GRAB: Death comes to all, but great achievements build a monument which shall endure until the sun grows cold. --Ralph Waldo Emerson ',
	'GRAB: Dont limit yourself. You can go as far as your mind lets you. What you believe, remember, you can achieve. --Mary Kay Ash',
	'GRAB: Dragonflies can fly up to 50 miles per hour.',
	'GRAB: Efficiency is doing things right; effectiveness is doing the right things. --Peter F. Drucker',
	'GRAB: Elephants purr like cats do, as a means of communication.',
	'GRAB: Feeling sorry for yourself, and your present condition, is not only a waste of energy but the worst habit you could possibly have. --Dale Carnegie ',
	'GRAB: Fish have gel-slime on their bodies that protects them from parasites.',
	'GRAB: Flying fish actually glide on wind currents above the surface of the water, sometimes up to 20 feet above the surface.',
	'GRAB: Foxes sometimes nip at the heals of cattle so the stomping of the cattle makes mice and other rodents come out of the ground, for the fox to eat.',
	'GRAB: Gamitin ang puso para alagaan ang taong malapit sayo. Gamitin ang utak para alagaan ang sarili mo. -Bob Ong',
	'GRAB: Germs only cause disease, right? But a common bacterium, E. Coli, found in the intestine helps us digest green vegetables and beans.',
	'GRAB: Great achievement is usually born of great sacrifice, and is never the result of selfishness. -Napoleon Hill',
	'GRAB: Half your bodys red blood cells are replaced every seven days.',
	'GRAB: Hearts will be practical only when they are made unbreakable. --The Wizard of Oz',
	'GRAB: Honeybees have hair on their eyes.',
	'GRAB: Hummingbirds flap their wings between 50 and 70 times a second!',
	'GRAB: I would rather have had one breath of her hair, one kiss from her mouth, one touch of her hand, than eternity without it. -City of Angels',
	'GRAB: If hair remains uncut, it can grow up to 5 feet long.',
	'GRAB: If you dont like something, change it. If you cant change it, change your attitude. Do not complain. -Maya Angelou',
	'GRAB: In one day your heart beats 100000 times.',
	'GRAB: In the arithmetic of love, one plus one equals everything, and two minus one equals nothing. -Mignon McLaughlin',
	'GRAB: In these dreams Ive loved you so, that by now I think I know what its like to be loved by you. I will love being loved by you. -The King and I',
	'GRAB: In times of trouble, dont ask why me? Instead ask, What do u want me to learn? Then trust God n keep on doing whats right. -Unknown',
	'GRAB: It is impossible to sneeze with your eyes open.',
	'GRAB: It takes food seven seconds to go from the mouth to the stomach via the esophagus.',
	'GRAB: It takes more muscles to frown than it does to smile.',
	'GRAB: Killer Whales are the only sea animal that outranks the Tiger Shark as top predator of the sea.',
	'GRAB: Kiss me. Kiss me as if it were the last time. -Casablanca',
	'GRAB: Kung hindi mo mahal and isang tao, wag ka nang magpakita ng motibo para mahalin ka nya. -Bob Ong',
	'GRAB: Lahat naman ng tao sumeseryoso pag tinamaan ng pagmamahal. Yun nga lang, hindi lahat matibay para sa temptasyon. -Bob Ong',
	'GRAB: Life has taught us that love does not consist in gazing at each other but in looking outward together in d same direction. -Antoine de Saint-Exupery',
	'GRAB: Life is a journey and it is love that makes that journey worthwhile. True love has no limits. -Unknown Author',
	'GRAB: Limasawa Island is where Ferdinand Magellan 1st landed in which gave way to the discovery of the Philippines and where the first mass was celebrated.',
	'GRAB: Love doesnt make the world go round. Love is what makes the ride worthwhile. -Franklin P. Jones',
	'GRAB: Love has nothing to do with what you are expecting to get, only what you are expecting to give. -Katherine Hepburn',
	'GRAB: Love is but the discovery of ourselves in others, and the delight in the recognition. -Alexander Smith',
	'GRAB: Maybe love is like luck. You have to go all the way to find it. -Robert Mitchum',
	'GRAB: Men always want to be a womans first love. Women have a more subtle instinct: What they like is to be a mans last romance. -Oscar Wilde',
	'GRAB: Minsan, its better for two people to break up, so they can grow up. It takes grown ups to make relationships work. -From Movie: One more Chance',
	'GRAB: Mt. Apo, the Philippines highest mountain at 10,311 feet above sea level, and considered as the “Grand-father of all Philippine Mountains”',
	'GRAB: Never let a problem to be solved become more important than the person to be loved. -Barbara Johnson',
	'GRAB: Nobody has ever measured, not even poets, how much the heart can hold. -Zelda Fitzgerald',
	'GRAB: Of the eight known species of giant clams in the world, seven are found in the Philippines.',
	'GRAB: One kind of insect called a spittlebug, lays its eggs in a big nest of saliva bubbles. I guess no predator would look for a meal in there!',
	'GRAB: Only male crickets can chirp.',
	'GRAB: Opportunity is missed by most people because it is dressed in overalls and looks like work. -Thomas Edison',
	'GRAB: Out of every 1000 Mosquitos, one female carries a disease that could be fatal to humans.',
	'GRAB: People used to think the Manatee was a mermaid.',
	'GRAB: Prayers s d best armor against trials. A heart to heart talk wid Jesus will lessen r burden for HE will always bless those hu believe in His name.',
	'GRAB: Remember your leaders, who spoke the word of God to you. Imitate their faith. Jesus Christ is the same yesterday, today and forever. --Hebrews 13:7-8',
	'GRAB: Remember, happiness does not depend upon who you are or what you have; it depends solely on what you think. --Dale Carnegie',
	'GRAB: Salamanders breath through their skin.',
	'GRAB: San Juanico Strait - said to be the narrowest yet the most navigable strait in the world.',
	'GRAB: Scallops swim with jet-propelled speed by clapping its shell open and shut.',
	'GRAB: Sea horses pull themselves around with their chins leading them.',
	'GRAB: Sea snakes are the most poisonous snakes in the world.',
	'GRAB: Some ducks and geese can fly as much as 332 miles a day!',
	'GRAB: Some fish have eyes that are the same size as their stomach!',
	'GRAB: Some male spiders pluck their cobwebs like a guitar, to attract female spiders.',
	'GRAB: Someday my wish is for him to hold me in his arms, in a sea of deep blue, together at last, together as two. -Cant Buy Me Love',
	'GRAB: SORBETES. This sweet treat was concocted in the early 1920s, a time where a single centavo could buy you almost anything.',
	'GRAB: Start by doing what is necessary, then do what is possible, and suddenly you are doing the impossible. --St. Francis of Assisi',
	'GRAB: Storm clouds may gather and stars may collide, but I love you, until the end of time. --Moulin Rouge',
	'GRAB: Success is the ability to go from one failure to another with no loss of enthusiasm. --Sir Winston Churchill ',
	'GRAB: Take this day to relax and ponder about the life u have. Ask God for the blessings n guidance through the rest of your earthly life. -Unknown',
	'GRAB: That dust on rugs and your furniture is not only dirt. Its mostly made of dead skin cells.',
	'GRAB: The 14-foot-long narwhal is a whale whose tooth can reach up to eight feet long!',
	'GRAB: The average American over fifty will have spent 5 years waiting in lines.',
	'GRAB: The average growth of hair is half an inch per month.',
	'GRAB: The average housefly lives for one month.',
	'GRAB: The average human dream lasts only 2 to 3 seconds.',
	'GRAB: The average person has at least seven dreams a night.',
	'GRAB: The Basilica of San Sebastian is the only steel church in Asia and was the second building to be made out of steel, next to the Eiffel Tower in Paris.',
	'GRAB: The bee frog of Africa is no bigger than a bee.',
	'GRAB: The big secret in life is that there is no big secret. Whatever your goal, you can get there if you are willing to work. -Oprah Winfrey ',
	'GRAB: The black-necked cobra, which lives mostly in Africa, spits its venom into the eyes of its victim, to cause it blindness.',
	'GRAB: The common garden worm has five pairs of hearts.',
	'GRAB: The dipper bird builds nests behind waterfalls for protection.',
	'GRAB: The earliest fossil cockroach is about 280 million years old – 80 million years older than the first dinosaurs!',
	'GRAB: The Egyptian vulture uses stones to smash ostrich eggs.',
	'GRAB: The emperor penguin is playful, and often times lies on its chest and side to slide along the ice and snow.',
	'GRAB: The exotic jeepney is the Filipino version of the jitney, the taxi/minibus that travels along a fixed route, found in many countries.',
	'GRAB: The farthest you can see with the naked eye is 2.4 million light years away! Thats the distance to the giant Andromeda Galaxy.',
	'GRAB: The faster kangaroos hop, the less energy they use.',
	'GRAB: The female black widow’s poison is 15 times deadlier than a rattlesnake’s!',
	'GRAB: The fiddler crab can grow a new claw when it loses one of its own.',
	'GRAB: The first step to getting the things you want out of life is this: Decide what you want. --Ben Stein',
	'GRAB: The flying fox of Africa has a wingspan of fifty inches!',
	'GRAB: The girl who breaks up with you because she doesnt believe in serious relationships will always marry the next guy she meets. -100 days of Summer',
	'GRAB: The guanaco of South America, a cousin of the camel, has pads on its feet to keep its feet from burning on desert sand or freezing in mountain snow.',
	'GRAB: The heaviest insect in the world weights 2.5 ounces.',
	'GRAB: The human body is 75% water.',
	'GRAB: The largest bird egg ever laid was laid millions of years ago by the Madagascar, or the elephant bird.',
	'GRAB: The largest fish in the world, the Whale Shark, locally known as Butanding, regularly swims to the Philippine waters.',
	'GRAB: The leatherback is the biggest sea turtle, and it can weigh as much as 1500 pounds.',
	'GRAB: The lung fish can live out of water for as long as four years!',
	'GRAB: The mandrill baboon has a red nose, blue cheeks, and an orange beard!',
	'GRAB: The mayfly only lives for 8 hours!',
	'GRAB: The most complicated achievements of thought are possible without the assistance of consciousness. - Sigmund Freud',
	'GRAB: The person who sends out positive thoughts activates the world around him positively and draws back to himself positive results. -Norman P.',
	'GRAB: The popular toy, the yoyo, was invented by 16th century hunters in the Philippines.',
	'GRAB: The praying mantis is the only insect that can look behind its shoulders.',
	'GRAB: The secret to staying young is to live honestly, eat slowly, and lie about your age. - Lucille Ball',
	'GRAB: The seeds of greatness are in you. God never created you to be nobody but a real somebody. God values you so much and loves you more than you know.',
	'GRAB: The smallest bones in the human body are in your ear!',
	'GRAB: The smallest fish in the world are the pygmy goby and the Luzon goby, which are only one-half-inch long when they are full grown, from the Philippines.',
	'GRAB: The snapping shrimp, only 1 1/2 inches long, makes a noise with its one big claw, which sounds exactly like a firecracker.',
	'GRAB: The stonefish, which lives off the coast of Australia, is the most poisonous fish in the world.',
	'GRAB: The strongest bone in your body is the femur (thighbone), and its hollow!',
	'GRAB: The width of your armspan stretched out is the length of your whole body.',
	'GRAB: Theodore Roosevelt was the U.S. President with the most pets, including a lion, hyena, wildcat, five bears, and many more!',
	'GRAB: There are 12000 or so species of seashells in the Philippines. The Conus Gloriamaris or "Glory of the Sea" is the rarest and most expensive in the world.',
	'GRAB: There are about 100 billion birds in the world, and about 6 billion of them make their homes in the United States.',
	'GRAB: There are as many hairs per square inch on your body as a chimpanzee.You dont see all of them because most are too fine and light to be noticed.',
	'GRAB: There are two primary choices in life: To accept conditions as they exist, or accept the responsibility for changing them. -Denis Waitley ',
	'GRAB: There are worms in Australia that are over 4 Feet Long!',
	'GRAB: There is only one insect that can turn its head - the praying mantis.',
	'GRAB: There were about 300 bones in your body when you were born, but by the time you reach adulthood you only have 206.',
	'GRAB: Thought for the day: "Always be d reason of someones happiness never just a part of it. Be a part of someones sadness never d reason for it." -Kia Ren',
	'GRAB: Throughout lyf people wil make u mad, disrespect u n treat u bad. Let God deal w d things dey do, cause hate in ur hart wil consume u too. -Will Smith',
	'GRAB: To love and win is the best thing. To love and lose, the next best. -William M. Thackeray',
	'GRAB: Today, the ostrich is the bird that lays the largest eggs.',
	'GRAB: Vultures can soar for hours without one beat of their wings.',
	'GRAB: We dont stop playing because we grow old; we grow old because we stop playing. - George Bernard Shaw',
	'GRAB: What we have once enjoyed we can never lose. All that we love deeply becomes a part of us. -Helen Keller',
	'GRAB: When an octopus gets angry, it shoots a stream of black “ink”.',
	'GRAB: When our attitude towards ourselves is big n our attitude toward other is generous n merciful, we attract big n generous portions of success. - W. C.',
	'GRAB: When two lovebirds appear to be kissing, they are actually grooming each other with their bills to keep clean and neat.',
	'GRAB: When you know what will make you happy, you grab the opportunity. Sometimes you dont have a second chance. -from When Love Begins',
	'GRAB: When you wake up in the morning you are at taller than when you go to sleep.',
	'GRAB: Who ran to help me when I fell, And would some pretty story tell, Or kiss the place to make it well? My Mother. Happy Mothers Day! -Kristie Paulm',
	'GRAB: Without a heart I can never really know what it would be like to love someone, or ever really understand trashy novels. -Wizard of Oz',
	'GRAB: You blink your eyes over 10,000,000 a year.',
	'GRAB: You were made perfectly to be loved - and surely I have loved you, in the idea of you, my whole life long. -Elizabeth Barrett Browning',
	'GRAB: Your blood takes a very long trip through your body. If you could stretch out all of a humans blood vessels, they would be about 60000 miles long.',
	'GRAB: Your brain is 80% water.',
	'GRAB: Your brain is move active and thinks more at night than during the day.',
	'GRAB: Your fingernails grow almost four times as fast as your toenails.',
	'GRAB: Your forearm (from inside of elbow to inside of wrist) is the same length as your foot.',
	'GRAB: Your mouth uses 75 muscles when you speak!',
	'GRAB: Your thigh bone is stronger than concrete.',
	'GRAB: Your tongue has 3000 taste buds.',
	'GRAB: Your tongue, eye, and jaw muscles are among the strongest muscles in your body.'
);

?>